#!/usr/bin/env python3
"""
Convert an image to C64 hires bitmap format for use as a gameplay background.

Usage:
    python convert_hires.py input.jpg [output.asm]

Output: ACME assembly with hires bitmap data (8000 bytes) and screen RAM colors (1000 bytes).
Hires mode: 320x200, 1 bit per pixel, 2 colors per 8x8 cell.
"""

import sys
import os
from pathlib import Path

# C64 color palette (RGB values)
C64_PALETTE = [
    (0x00, 0x00, 0x00),  # 0  Black
    (0xFF, 0xFF, 0xFF),  # 1  White
    (0x88, 0x00, 0x00),  # 2  Red
    (0xAA, 0xFF, 0xEE),  # 3  Cyan
    (0xCC, 0x44, 0xCC),  # 4  Purple
    (0x00, 0xCC, 0x55),  # 5  Green
    (0x00, 0x00, 0xAA),  # 6  Blue
    (0xEE, 0xEE, 0x77),  # 7  Yellow
    (0xDD, 0x88, 0x55),  # 8  Orange
    (0x66, 0x44, 0x00),  # 9  Brown
    (0xFF, 0x77, 0x77),  # 10 Pink
    (0x33, 0x33, 0x33),  # 11 Dark Grey
    (0x77, 0x77, 0x77),  # 12 Grey
    (0xAA, 0xFF, 0x66),  # 13 Light Green
    (0x00, 0x88, 0xFF),  # 14 Light Blue
    (0xBB, 0xBB, 0xBB),  # 15 Light Grey
]

def color_distance(c1, c2):
    return sum((a - b) ** 2 for a, b in zip(c1, c2))

def find_nearest_c64_color(rgb):
    min_dist = float('inf')
    best_idx = 0
    for idx, pal_color in enumerate(C64_PALETTE):
        dist = color_distance(rgb, pal_color)
        if dist < min_dist:
            min_dist = dist
            best_idx = idx
    return best_idx

def load_image(filename):
    """Load image and return 320x200 C64 color index array."""
    try:
        from PIL import Image
    except ImportError:
        print("Error: PIL/Pillow not installed. Run: pip install Pillow")
        sys.exit(1)

    img = Image.open(filename).convert('RGB')
    if img.size != (320, 200):
        img = img.resize((320, 200), Image.Resampling.LANCZOS)

    pixels = []
    for y in range(200):
        row = []
        for x in range(320):
            rgb = img.getpixel((x, y))
            row.append(find_nearest_c64_color(rgb))
        pixels.append(row)
    return pixels

def convert_to_hires_bitmap(pixels):
    """
    Convert 320x200 indexed pixels to C64 hires bitmap format.

    Returns:
        (bitmap_data, screen_ram)
        - bitmap_data: 8000 bytes (1 bit per pixel, 8 bytes per 8x8 cell)
        - screen_ram: 1000 bytes (high nibble=foreground, low nibble=background per cell)
    """
    bitmap_data = bytearray(8000)
    screen_ram = bytearray(1000)

    cell_idx = 0
    for char_row in range(25):
        for char_col in range(40):
            # Collect all pixels in this 8x8 cell
            cell_pixels = []
            for y in range(8):
                py = char_row * 8 + y
                for x in range(8):
                    px = char_col * 8 + x
                    if py < 200 and px < 320:
                        cell_pixels.append(pixels[py][px])
                    else:
                        cell_pixels.append(0)

            # Find the two most common colors in this cell
            color_counts = {}
            for c in cell_pixels:
                color_counts[c] = color_counts.get(c, 0) + 1

            sorted_colors = sorted(color_counts.keys(), key=lambda c: -color_counts[c])

            # Background = most common (0-bit), Foreground = second most common (1-bit)
            bg_color = sorted_colors[0]
            fg_color = sorted_colors[1] if len(sorted_colors) > 1 else bg_color

            screen_ram[cell_idx] = (fg_color << 4) | bg_color

            # Convert pixels to bitmap bits
            for y in range(8):
                byte_val = 0
                for x in range(8):
                    pixel_color = cell_pixels[y * 8 + x]
                    # Determine if this pixel is closer to fg or bg
                    if pixel_color == fg_color:
                        bit = 1
                    elif pixel_color == bg_color:
                        bit = 0
                    else:
                        # Map to nearest of the two available colors
                        dist_fg = color_distance(C64_PALETTE[pixel_color], C64_PALETTE[fg_color])
                        dist_bg = color_distance(C64_PALETTE[pixel_color], C64_PALETTE[bg_color])
                        bit = 1 if dist_fg <= dist_bg else 0
                    byte_val = (byte_val << 1) | bit

                bitmap_data[cell_idx * 8 + y] = byte_val

            cell_idx += 1

    return bitmap_data, screen_ram

def write_asm_output(bitmap_data, screen_ram, output_path):
    """Write ACME assembly output file."""
    with open(output_path, 'w') as f:
        f.write("; ============================================================================\n")
        f.write("; Level 2 Background - Hires Bitmap Data\n")
        f.write("; Generated by convert_hires.py\n")
        f.write("; ============================================================================\n")
        f.write("; Hires bitmap: 8000 bytes bitmap + 1000 bytes screen RAM colors\n")
        f.write("; Copied to GAMEPLAY_BITMAP ($4000) and GAMEPLAY_SCREEN ($6000) at runtime\n")
        f.write("; ============================================================================\n\n")

        f.write("; Bitmap data (8000 bytes) - stored here, copied to $4000 at runtime\n")
        f.write("LEVEL2_BITMAP:\n")
        for i in range(0, len(bitmap_data), 16):
            chunk = bitmap_data[i:i+16]
            hex_bytes = ", ".join(f"${b:02X}" for b in chunk)
            f.write(f"        !byte {hex_bytes}\n")

        f.write("\n; Screen RAM colors (1000 bytes) - copied to $6000 at runtime\n")
        f.write("LEVEL2_SCREEN:\n")
        for i in range(0, len(screen_ram), 16):
            chunk = screen_ram[i:i+16]
            hex_bytes = ", ".join(f"${b:02X}" for b in chunk)
            f.write(f"        !byte {hex_bytes}\n")

        f.write("\n; End of level 2 background data\n")

def main():
    if len(sys.argv) < 2:
        print("Usage: python convert_hires.py input.jpg [output.asm]")
        sys.exit(1)

    input_file = sys.argv[1]
    if not os.path.exists(input_file):
        print(f"Error: File not found: {input_file}")
        sys.exit(1)

    script_dir = Path(__file__).parent
    output_path = script_dir.parent / "level2_bg.asm" if len(sys.argv) < 3 else Path(sys.argv[2])

    print(f"Loading image: {input_file}")
    pixels = load_image(input_file)

    print("Converting to C64 hires bitmap format...")
    bitmap_data, screen_ram = convert_to_hires_bitmap(pixels)

    print(f"Bitmap data: {len(bitmap_data)} bytes")
    print(f"Screen RAM: {len(screen_ram)} bytes")

    print(f"Writing output: {output_path}")
    write_asm_output(bitmap_data, screen_ram, output_path)
    print("Done!")

if __name__ == "__main__":
    main()
